steps:

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: /bin/bash
    args: 
    - -c
    - |
      git fetch --depth=2 origin main
      echo hello
      git  log
      git --no-pager diff --name-only HEAD^ HEAD | grep "/" | cut -d/ -f1 | sort | uniq > /workspace/diff.txt

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/bash
    args: 
    - -c
    - |
       echo "Then we saved " $(cat /workspace/diff.txt)
       while read line
       do 
       echo $line; 
       echo "Building $line ... "
       config="${line}/cloudbuild.yaml"
       echo $config
       if [[ ! -f "${config}" ]]; then
        echo "no such file"
        continue
       fi
       gcloud builds submit $line --config=${config}
       done < /workspace/diff.txt


options:
 logging: CLOUD_LOGGING_ONLY